version: '3.9'

services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    env_file: ./.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - '5407:5432'
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name
      TZ: 'GMT+8'
      PGTZ: 'GMT+8'
    networks:
      - book_ticket_network

networks:
  book_ticket_network:
    name: book_ticket_network
    driver: bridge
